- name: check nginx installed
  yum:
    list: nginx1
  register: pkg
  #when: "'tag_Name_dc_stg_web_original_001' in inventory_hostname"
  ignore_errors: True

- name: Enable amazon-linux-extras
  command: amazon-linux-extras enable nginx1
  become: yes
  when: pkg.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: Install nginx
  yum:
    name: nginx
    state: present
  when:
    - pkg.results | selectattr("yumstate", "match", "installed") | list | length == 0 
  ignore_errors: True

- name: file copy
  template: src=files/sample.html
        dest=/usr/share/nginx/html/index.html
        owner=ec2-user
        group=ec2-user
        mode=0644
  when: "'duplicate' in ec2_tag_Name"


- name: nginx_restart
  systemd:
    name: nginx
    enabled: yes
    state: restarted
  become: yes


